apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  namespace: nestjs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nestjs-pod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-pod
  template:
    metadata:
      labels:
        app: nestjs-pod
    spec:
      containers:
      - name: nodejs
        image: node:18
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
