
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deploy
  namespace: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-deploy
  template:
    metadata:
      labels:
        app: nestjs-deploy
    spec:
      containers:
      - name: nestjs-demo
        image: jsadev/nestjs-demo:release
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
