apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  labels:
    run: nestjs-service
  namespace: nestjs
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    run: nestjs-deploy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deploy
  namespace: nestjs
spec:
  replicas: 1
  selector:
    name: nestjs-deploy
    matchLabels:
      run: nestjs-deploy
  template:
    metadata:
      labels:
        run: nestjs-deploy
    spec:
      containers:
      - name: nestjs-demo
        image: jsadev/nestjs-demo:release
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
