apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
  namespace: nestjs
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: nestjs-app
  type: ClusterIP